version: '3.8'

services:
  nodo-a:
    image: cockroachdb/cockroach:latest
    container_name: nodo-a
    hostname: nodo-a
    ports:
      - "26259:26257"
      - "8086:8080"
    volumes:
      - nodoa:/cockroach/cockroach-data
    command: start-single-node --insecure --advertise-addr=nodo-a

  nodo-b:
    image: cockroachdb/cockroach:latest
    container_name: nodo-b
    hostname: nodo-b
    ports:
      - "26260:26257"
      - "8087:8080"
    volumes:
      - nodob:/cockroach/cockroach-data
    command: start --insecure --store=node2 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=nodo-a:26257 --advertise-addr=nodo-b

  nodo-c:
    image: cockroachdb/cockroach:latest
    container_name: nodo-c
    hostname: nodo-c
    ports:
      - "26261:26257"
      - "8088:8080"
    volumes:
      - nodoc:/cockroach/cockroach-data
    command: start --insecure --store=node3 --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080 --join=nodo-a:26257 --advertise-addr=nodo-c

volumes:
  nodoa:
  nodob:
  nodoc:
