spring:
  application:
      name: SERVICE-NOTIFICACIONES
  datasource:
    url: jdbc:postgresql://localhost:26259/bd_notificaciones_eventos?user=root&password=
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update #create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5674
    username: admin
    password: admin
server:
  port: 0


